name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ docker_ci ]

env:
  DOCKER_IMAGE_NAME: mlops-pipeline
  DOCKERHUB_USERNAME: akash171

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run training script
      run: python train.py # Corrected: 'train.py' is expected in the root, 'cd src' removed.
    
    - name: Verify model files exist
      run: |
        ls -la models/
        test -f models/linear_regression_model.joblib
        test -f models/test_data.joblib
    
    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }}:latest .
    
    - name: Run Docker container verification
      run: |
        docker run --rm ${{ env.DOCKER_IMAGE_NAME }}:latest python src/predict.py
    
    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.akash171 }} # Corrected: Username must come from GitHub Secrets.
        password: ${{ secrets.dckr_pat_4tkfGjT0lXeSD0Xm8onFcIvJ6UI}}    # Corrected: Password (token) must come from GitHub Secrets.
    
    - name: Push Docker image to Docker Hub
      if: success()
      run: |
        docker tag ${{ env.DOCKER_IMAGE_NAME }}:latest ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest