# .github/workflows/ci.yml
name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - docker_ci # Trigger on pushes to docker_ci branch

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python environment and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt # Install dependencies for train.py on runner

      - name: Run train.py to generate model file
        run: python train.py # Generates linear_regression_model.joblib

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and tag Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops_assignment_3:latest # REPLACE with YOUR Docker Hub username!

      - name: Run Docker container for verification
        run: docker run ${{ secrets.DOCKER_USERNAME }}/mlops_assignment_3:latest python predict.py